### ISSUE TITLE
still displays everything

### ISSUE THREAD

**Issue by Necrofiend13** [ahungry/NoMoreMoo#1]
Hello, having an issue where the addon still tell me that it is ignoring a specific message in chats and then displays the message anyway in my chat, so, at a loss as to how to prevent this since there are limited features using /nmm atm. Thanks for any advice and information

**Comment by ahungry** [comment]
Hi - the latest version (from commit bfc8acf8adcfa05f292e34b09d7504af6affbadf done on Friday) should actually suppress it - I had it just noting the message was (would be) blocked prior to that for debugging/development purposes.

If you pull the latest code, is it still not working as expected?

I should add - currently it only filters the "world" (/join world) chat group and one I made for testing (/join nmm) - spam that occurs in other channels (/say, /guild, /whisper etc.) will still show up - this could be annoying if it is happening in `<Newcomers>` guild - so I may extend it to handle that as well (maybe optionally) - as most other guild chats should probably never be filtered.

**Comment by Necrofiend13** [comment]
Yes! I believe it's good now. =]
Been a whole hour and not one goldspam or "Moo"

Thank you very much
